on:
  pull_request:
    types: [closed]

name: Reindex Algolia Docsearch
jobs:
  reindex-docsearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Reindex
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'algolia-config.json'
